appVersion: v1
kind: Deployment
metadata:
  name: myapp-deployment
  lables:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
          name: nginx-3
          labels:
            app: myapp
    spec:
      containers:
      - name: nginx-depl
        image: nginx