apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango-express
  labels:
    app: mango-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango-express
  template:
    metadata:
      labels:
         app: mango-express
    spec:
      containers:
      - name: mango-express
        image: mango-express
        ports:
        - containerPort: 8081
        env: 
         - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valuesFrom:
             secretKeyRef:
               name: mongodb-secret
               key: mongodb-root-username
         - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valuesFrom:
             secretKeyRef:
               name: mongodb-secret
               key: mongodb-root-password  
         - name: ME_CONFIG_MONGODB_SERVER
            valuesFrom:
             configMapKeyRef:
               name: mongodb-configmap
               key: database_url
         
         
---
apiVersion: v1
Kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongoexpress
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 8081
      targetport: 8081
      nodeport: 30000
               