


---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: croniptpoloadfromlrs
spec:
  schedule: "0 0/2 * * * ?"
  jobTemplate:
   spec:
     template:
       spec:
         containers:
           - name: croniptpoloadfromlrs
             image: e-dpiac-docker-local.docker.lowes.com/iptpoloadfromlrs:0.0.1-3-d02483272d
           
      command:
        - /bin/sh
        - -c
        - date;
      restartPolicy: OnFailure



apiVersion: v1
kind: ConfigMap
metadata:
  name: adoptnext-cm
data:
  FIRST_NAME: adopt
  SECOND_NAME: next





apiVersion: batch/v1
kind: CronJob
metadata:
name: hello
spec:
schedule: "*/1 * * * *"
jobTemplate:
spec:
template:
spec:
containers:
- name: hello
image: busybox
imagePullPolicy: IfNotPresent
command:
- /bin/sh
- -c
- date; echo Hello from the Kubernetes cluster
restartPolicy: OnFailure